### ISSUE TITLE
Validation Error: A sampler points to a texture unit used by fixed function with an incompatible target.

### ISSUE THREAD

**Issue by dentmaged** [oreonengine/oreon-engine#21]
When running Oreon Engine for the first time (on Windows 10 Pro v10.0.15063), it crashes: Here is the log:
```
OpenGL version: 4.3.0 - Build 20.19.15.4531 bytes
Max Geometry Uniform Blocks: 35372 bytes
Max Geometry Shader Invocations: 36442 bytes
Max Uniform Buffer Bindings: 35375 bytes
Max Uniform Block Size: 35376 bytes
Max SSBO Block Size: 37086 bytes
engine.shaders.motionblur.PixelVelocityShader Validation Error: A sampler points to a texture unit used by fixed function with an incompatible target.
```

Here is information about my computer (the graphics are integrated):
```
Processor: Intel(R) Core(TM) i5-4258U CPU @ 2.40 GHz
Running Intel(R) Iris(TM) Graphics 5100
Shader Version: 5.0
OpenGL Version: 4.3
OpenCL Version: 1.2
Physical Memory: 4004 MB
```

**Comment by dentmaged** [comment]
I was able to run the demo by commenting out the code that printed out the message. However, the performance is very bad and the maximum FPS I got was 9. When maximising the window, I see a zoomed in image of I believe the bottom left hand corner. As well as that, it took me about 21 seconds to load one of the models. Here is the output of that run:
```
OpenGL version: 4.3.0 - Build 20.19.15.4531 bytes
Max Geometry Uniform Blocks: 35372 bytes
Max Geometry Shader Invocations: 36442 bytes
Max Uniform Buffer Bindings: 35375 bytes
Max Uniform Block Size: 35376 bytes
Max SSBO Block Size: 37086 bytes
no material in polygon of:  Dome
obj loading time : 16ms
no material in polygon of:  Dome
obj loading time : 6ms
obj loading time : 7ms
obj loading time : 23ms
obj loading time : 781ms
obj loading time : 22308ms
obj loading time : 13ms
obj loading time : 1758ms
obj loading time : 6ms
obj loading time : 11024ms
obj loading time : 12ms
obj loading time : 118ms
obj loading time : 72ms
```

**Comment by oreonengine** [comment]
The crash with error message "A sampler points to a texture unit used by fixed function with an incompatible target" is a know bug with Intel HD/Iris Graphics GPU's. The bug isn't fixed yet...

21 secs for 'Tree02'-model are realistic with 4th-gen mobile CPU. The model is very very high-poly, aswell the 'Palm01'-model. My CPU (Intel i5-6600K) needs 2sec for 'Tree01'.
Maybe you could comment out int the Main-Class the lines where Tree02 and Palm01 are added to the scenegraph

**Comment by dentmaged** [comment]
@oreonengine About the crash, it seems like it's a problem with Intel's drivers. I commented out the lines (in Main) and the performance is still quite bad. However the load time is much faster. I also lowered the number of samples and that didn't seem to have any (noticeable) affect on FPS either.

As well as that, I have tried to fix the windows maximising problem. I've never done GLFW before though. Anyhow, I added a window resize hook to GLFW and I call glViewport, but that still doesn't have any affect.

**Comment by oreonengine** [comment]
the resize will be fixed within my next commit. I've done a big rework coming up with ne next commit to open the doors for Vulkan and Android support

**Comment by dentmaged** [comment]
@oreonengine Oh nice! Does it include any graphical optimisations?

**Comment by oreonengine** [comment]
just performance updates and a smoother Camera-Mouse Rotation

**Comment by dentmaged** [comment]
There is a 3rd party Intel driver called PHDGD. I'm going to try it out and see if it fixes this bug. I'll also report to you about the performance.
