### ISSUE TITLE
Coordinate System?

### ISSUE THREAD

**Issue by realcake** [oreonengine/oreon-engine#22]
What kind of scale does this engine support? I keep running into a roadblock when using other game engines. Libgdx only supports a floating point coordinate system, so creating a realistic solar system becomes very difficult as millimeter accuracy becomes impossible with only 7 decimals of accuracy.

How does this engine work with massive scale?

**Comment by oreonengine** [comment]
it's a floating point coordinate system. I set the zFar value to 10.000, to prevent z-fighting as much as possible
