### ISSUE TITLE
Seriouse Issue in GLFWInput class

### ISSUE THREAD

**Issue by Speiger** [oreonengine/oreon-engine#23]
https://github.com/oreonengine/oreon-engine/blob/master/oreonengine/oe-system-desktop/src/main/java/org/oreon/system/desktop/GLFWInput.java

All the fields that contain the information about keys pressed and other things have to be replaced with hashSets. Linked if there is a iteration.
Arraylists for containsChecks are really really really really really really really really really bad.
they go through every entry in the List to compare that entry with all the other entries in order ofcourse.
HashSet convert the number you ask for into a hashcode and that links directly into the entry that would contain it. That means less operations no matter how many keys you have added.

Also with hashSets you dont need to make a "Contains" key  check since if it was already added then it doesnt create duplicated entry.
Only downside is the order is hashbased for iteration. If you want ordered by when it was added you use linkedhashset (in general you use linkedhashsets for iteration since the hashset is not good by default to do that)

**Comment by oreonengine** [comment]
Thank you very much, this will gonna be fixed soon!
