### ISSUE TITLE
Missing jar during maven clean install

### ISSUE THREAD

**Issue by TomaszNaglik** [oreonengine/oreon-engine#24]
Hey guys,

when connecting maven to my local repository I get the following problem.
Do you know perhaps why this is the case?
 

> Failed to execute goal on project oe-core-opengl: Could not resolve dependencies for project org.oreon.core:oe-core-opengl:jar:2.1.0: Failure to find org.oreon.core:oe-core:jar:2.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by Krono5** [comment]
I'm not sure if this will help, but for me I went to lwjgl's website and downloaded the custom pom.xml with everything in it in the maven section. You then have to convert your project to a maven project and update it. In the dependency section on the pom.xml, you should see that all libraries we're updated successfuly.

**Comment by oreonengine** [comment]
TomaszNaglik did you clean install the oe-main module? In order to build you need to convert to maven project as Krono5 explained, then clean install the oe-main module. Now you can build the oe-demo executables by clean install oe-demo-gl
