### ISSUE TITLE
Shader won't compile with an AMD graphic card

### ISSUE THREAD

**Issue by YvesBoyadjian** [oreonengine/oreon-engine#26]
Hi, I have an AMD Rx Vega and cannot run the oreon engine in OpenGL (oe-gl-demo). I have the message : 

org.oreon.core.gl.shaders.TransparencyBlendShader Validation failed! - Different sampler types for same sample texture unit in fragment shader.

The oe-vk-demo doesn't work either. I have the messages : 

Radeon RX Vega
ERROR OCCURED: Vertex shader consumes input at location 0 but not provided
ERROR OCCURED: Vertex shader consumes input at location 1 but not provided

I have tried it at work on a Quadro K2200 and the opengl version  works perfectly.

Thanks for your work, at last great graphics in java !

**Comment by oreonengine** [comment]
I did a new commit in vulkan, it runs now :) vulkan is still in progress, there can be sometimes commits where it fails to run :)

regarding the compile error, I detected the same error only on intel hd graphics, but seems the RX Vega has the same issues :( still I don't know why it's not compiling, I though the intel HD graphics are just too bad to handle many samplers in one shader, but theat theory is not applicable on the RX Vega :D

**Comment by YvesBoyadjian** [comment]
It is a well known fact that OpenGL Nvidia driver is more "permissive" than OpenGL AMD driver. When you do something not strictly compliant with the OpenGL standard, it will often be OK with an Nvidia card, but unfortunately not always with an AMD.
