### ISSUE TITLE
Gradle and Maven support

### ISSUE THREAD

**Issue by archenroot** [oreonengine/oreon-engine#3]
Hi, 

I am trying to create maven and gradle support for this project. One question, have you already migrated to latest LWJGL 3.*?

Thanks for this project!

**Comment by oreon3D** [comment]
Hi,

not yet mate, I considered to integrate maven into the project, but I did not have time to implement it. I have no experience with gradle, but both maven and gradle support would be awesome.
An upgrade to lwjgl 3 is on my TODO list for the next month.

Kind regards

**Comment by oreon3D** [comment]
Lwjgl 3 Migration in process now

**Comment by archenroot** [comment]
:-) you are a hero!

2017-06-19 16:03 GMT+02:00 Fynn <notifications@github.com>:

**Comment by oreon3D** [comment]
if you successfull integrate maven and/or gradle you can do a pull request and i will merge it :)

**Comment by oreon3D** [comment]
Maven support will come along with Lwjgl 3 migration

**Comment by archenroot** [comment]
I will work on that over this weekend :-) will update.

2017-06-20 12:21 GMT+02:00 Fynn <notifications@github.com>:

**Comment by oreon3D** [comment]
lwjgl 3 with Maven is stable now in branch 'lwjgl3-update'.
There are still a few trivial things to adjust with Input system and user GUI, I will merge it when I finished these things.
