### ISSUE TITLE
Shader filter file PixelVelocity.comp not found, causing NPE (Linux)

### ISSUE THREAD

**Issue by aromanelli** [oreonengine/oreon-engine#35]
Class ResourceLoader is throwing a NPE, while trying to read the file "../shaders/filter/motionBlur/PixelVelocity.comp", as that file does not exist.

However, the file "pixelVelocity.comp" does exist (see screenshot).

Running Ubuntu Budgie v18.04, so I'm assuming its probably a 'developed in Windows where character-case does not matter, and trying to run via IJ on Linux, where case-sensitivity is a thing' thing.

![oreon exception pixelvelocity](https://user-images.githubusercontent.com/409304/44291416-0bcfce00-a233-11e8-8a71-5a430a33495e.png)

**Comment by RubenWalraevens** [comment]
Linux is very sensitive on capitals while Windows just doesn't really care.

Anyway, this is an easy fix. Just lower the capital P.

**Comment by aromanelli** [comment]
I've created a pull request to fix this, and a couple of other issues I found, related to the same Windows vs. Linux filename issues.  https://github.com/oreonengine/oreon-engine/pull/36

**Comment by aromanelli** [comment]
Ok, put in a pull request.  One thing to note, I only fixed what I saw based on running the two demo classes, GLOreonworlds, and VkOreonworlds.  There may be more to fix, OS-compatability wise, that did not manifest from just running the demos.

**Comment by oreonengine** [comment]
Alright, thank you :)

**Comment by oreonengine** [comment]
So, should I close this issue and you open another one or should I let it open?

**Comment by aromanelli** [comment]
@oreonengine I'd say close it.  My previous comment was more of a disclaimer of me stating that I didn't test too much, just ran the demo apps.  There could be more file naming/pathing issues that the demos don't bring up to the surface.  We can always create new tickets for those.

**Comment by RubenWalraevens** [comment]
I will look into this tomorrow. Maybe I can address some other compatibility issues. Thank you!
