### ISSUE TITLE
Maths classes are calling getters on operand objects in some cases

### ISSUE THREAD

**Issue by ThomasKasene** [oreonengine/oreon-engine#39]
Has it been a conscious choice to use direct attribute access in some cases and getters in others in the maths DTOs? For example in `Vec3f`:

```java
public float dot(Vec3f r)
{
    return X * r.getX() + Y * r.getY() + Z * r.getZ();
}
```

Is there a reason for this? It seems to me that those getters add some unnecessary overhead, and I suspect they're called rather often per game tick.

Since you're already within the scope of `Vec3f`, you should be able to access the other instance's attributes directly as well as those of `this`'s, even though they're `private`. Were it up to me, I think I'd turn it into something like this unless there's some other reason that I haven't thought of:

```java
public float dot(Vec3f r)
{
    return X * r.X + Y * r.Y + Z * r.Z;
}
```

**Comment by aromanelli** [comment]
@ThomasKasene Just curious, is there an actual overhead in calling a method in Java, vs. just using a primitive value (assuming the getter is just returning the primitive value)?  I would imagine, at the lower levels, that a getter method reference lookup, vs. a primitive location lookup, would be ~ the same, performance wise?  Just honestly asking, never heard of performance issues concerns before from calling a getter/setter vs. just working with the primitive directly.

Generally speaking, having getters/setters allows you to have a 'hook' point if you need to add more logic associated with a primitive variable value, vs. having to change everywhere the primitive is used at, if you have to add the additional logic.  

Though I'd agree, in this specific use-case of a 3d graphics app, if using methods vs. primitives directly is an overhead, then primitives should be used.

**Comment by ThomasKasene** [comment]
Yep yep - you're correct that the compiler might do some optimizations under the hood, but as I understand it, this is not part of the Java specification, and so it's left to each compiler to decide whether or not to do it. The Just-In-Time compiler might do more inlining as well that we're not made aware of, but again, we're at the mercy of each JRE.

This is another thing that's probably worth profiling a little to see if replacing the getters with direct access is worth it or not, but the argument that encapsulating the attribute in a getter on the off-chance you'll add more logic to it isn't strong enough in my opinion, as these are quite fundamental mathematical concepts and we'd have bigger issues on our hands if they were suddenly to change.

Oh and by the way, I'm not saying "don't have getters in the maths classes" (although maybe they could've been generated by Lombok). The getters are an important part of the API that protects its clients from internal changes and refactorings.

Anyhow I just thought I'd raise the issue :) It might not be such a big one yet (if ever).

**Comment by oreonengine** [comment]
Ofc it is compiler dependent how e.g. getters are interpreted, but most likely every common compiler optimizes trivial function calls as much as possible in advance to reduce CPU instructions and overhead. Hence, simple getters are not really worth to worry about, for example iterate over a loop billions of time and call a getter each iteration...
However, thanks for open the issue and for your remarks ;)
